"""Add fc_acronym table

Revision ID: 5b60f30f1b0d
Revises: 336aaaae7666
Create Date: 2026-04-03 04:37:02.454413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b60f30f1b0d'
down_revision: Union[str, Sequence[str], None] = '336aaaae7666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fc_acronym',
    sa.Column('acronym_uid', sa.UUID(), nullable=False),
    sa.Column('acronym', sa.String(length=50), nullable=False),
    sa.Column('spelled_out', sa.String(length=500), nullable=True),
    sa.Column('created_by_uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_uid', sa.UUID(), nullable=True),
    sa.Column('locked_by_uid', sa.UUID(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['fc_user.user_uid'], ),
    sa.ForeignKeyConstraint(['locked_by_uid'], ['fc_user.user_uid'], ),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['fc_user.user_uid'], ),
    sa.PrimaryKeyConstraint('acronym_uid')
    )
    op.create_index('idx_acronym_text', 'fc_acronym', ['acronym'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_acronym_text', table_name='fc_acronym')
    op.drop_table('fc_acronym')
    # ### end Alembic commands ###
