"""Add Sprint 3 tables

Revision ID: 9c6cc21350e2
Revises: 003
Create Date: 2026-03-29 07:17:55.732651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c6cc21350e2'
down_revision: Union[str, Sequence[str], None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fc_ai_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['fc_user.user_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_usage_user', 'fc_ai_usage', ['user_uid'], unique=False)
    op.create_table('fc_event_log',
    sa.Column('event_uid', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_uid', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_uid', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversible', sa.Boolean(), nullable=False),
    sa.Column('reverse_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_uid'], ['fc_user.user_uid'], ),
    sa.PrimaryKeyConstraint('event_uid')
    )
    op.create_index('idx_event_actor', 'fc_event_log', ['actor_uid'], unique=False)
    op.create_index('idx_event_entity', 'fc_event_log', ['entity_uid', 'entity_type'], unique=False)
    op.create_index('idx_event_occurred', 'fc_event_log', ['occurred_at'], unique=False)
    op.create_index('idx_event_type', 'fc_event_log', ['event_type', 'entity_type'], unique=False)
    op.create_table('fc_user_preference',
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['fc_user.user_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_uid', 'key')
    )
    op.create_table('fc_fact',
    sa.Column('fact_uid', sa.UUID(), nullable=False),
    sa.Column('node_uid', sa.UUID(), nullable=False),
    sa.Column('current_published_version_uid', sa.UUID(), nullable=True),
    sa.Column('current_signed_version_uid', sa.UUID(), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_uid', sa.UUID(), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_by_uid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['fc_user.user_uid'], ),
    sa.ForeignKeyConstraint(['node_uid'], ['fc_node.node_uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retired_by_uid'], ['fc_user.user_uid'], ),
    sa.PrimaryKeyConstraint('fact_uid')
    )
    op.create_index('idx_fact_node', 'fc_fact', ['node_uid'], unique=False, postgresql_where='NOT is_retired')
    op.create_index('idx_fact_published', 'fc_fact', ['current_published_version_uid'], unique=False, postgresql_where='current_published_version_uid IS NOT NULL')
    op.create_table('fc_fact_version',
    sa.Column('version_uid', sa.UUID(), nullable=False),
    sa.Column('fact_uid', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('display_sentence', sa.Text(), nullable=False),
    sa.Column('canonical_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_date', sa.String(length=10), nullable=True),
    sa.Column('last_verified_date', sa.String(length=10), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('applies_to', sa.String(length=255), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('supersedes_version_uid', sa.UUID(), nullable=True),
    sa.Column('created_by_uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', display_sentence)", persisted=True), nullable=True),
    sa.CheckConstraint("state IN ('proposed','challenged','accepted','rejected','published','signed','withdrawn','retired')", name='ck_version_state'),
    sa.ForeignKeyConstraint(['created_by_uid'], ['fc_user.user_uid'], ),
    sa.ForeignKeyConstraint(['fact_uid'], ['fc_fact.fact_uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_version_uid'], ['fc_fact_version.version_uid'], ),
    sa.PrimaryKeyConstraint('version_uid')
    )
    op.create_index('idx_version_created_by', 'fc_fact_version', ['created_by_uid'], unique=False)
    op.create_index('idx_version_fact', 'fc_fact_version', ['fact_uid'], unique=False)
    op.create_index('idx_version_search', 'fc_fact_version', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_version_state', 'fc_fact_version', ['state'], unique=False)
    op.alter_column('fc_api_key', 'scopes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text('\'["read"]\'::jsonb'))
    op.alter_column('fc_import_session', 'effective_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fc_import_session', 'effective_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('fc_api_key', 'scopes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text('\'["read"]\'::jsonb'))
    op.drop_index('idx_version_state', table_name='fc_fact_version')
    op.drop_index('idx_version_search', table_name='fc_fact_version', postgresql_using='gin')
    op.drop_index('idx_version_fact', table_name='fc_fact_version')
    op.drop_index('idx_version_created_by', table_name='fc_fact_version')
    op.drop_table('fc_fact_version')
    op.drop_index('idx_fact_published', table_name='fc_fact', postgresql_where='current_published_version_uid IS NOT NULL')
    op.drop_index('idx_fact_node', table_name='fc_fact', postgresql_where='NOT is_retired')
    op.drop_table('fc_fact')
    op.drop_table('fc_user_preference')
    op.drop_index('idx_event_type', table_name='fc_event_log')
    op.drop_index('idx_event_occurred', table_name='fc_event_log')
    op.drop_index('idx_event_entity', table_name='fc_event_log')
    op.drop_index('idx_event_actor', table_name='fc_event_log')
    op.drop_table('fc_event_log')
    op.drop_index('idx_ai_usage_user', table_name='fc_ai_usage')
    op.drop_table('fc_ai_usage')
    # ### end Alembic commands ###
