"""Add fc_chat_session and fc_chat_message

Revision ID: f236640d1e37
Revises: f5c899b0e37e
Create Date: 2026-04-01 06:46:04.508396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f236640d1e37'
down_revision: Union[str, Sequence[str], None] = 'f5c899b0e37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fc_chat_session',
    sa.Column('chat_uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('program_node_uid', sa.UUID(), nullable=True),
    sa.Column('constraint_node_uids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('fact_filter', sa.String(length=10), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("fact_filter IN ('published', 'signed')", name='ck_chat_session_filter'),
    sa.CheckConstraint("mode IN ('smart', 'efficient')", name='ck_chat_session_mode'),
    sa.ForeignKeyConstraint(['program_node_uid'], ['fc_node.node_uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['fc_user.user_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_uid')
    )
    op.create_index('idx_chat_session_user', 'fc_chat_session', ['user_uid'], unique=False)
    op.create_table('fc_chat_message',
    sa.Column('message_uid', sa.UUID(), nullable=False),
    sa.Column('chat_uid', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('facts_loaded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_chat_message_role'),
    sa.ForeignKeyConstraint(['chat_uid'], ['fc_chat_session.chat_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_uid')
    )
    op.create_index('idx_chat_message_session', 'fc_chat_message', ['chat_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_message_session', table_name='fc_chat_message')
    op.drop_table('fc_chat_message')
    op.drop_index('idx_chat_session_user', table_name='fc_chat_session')
    op.drop_table('fc_chat_session')
    # ### end Alembic commands ###
