"""Tests for full-text search service: blended BM25, program grouping, is_program flag."""

import uuid
from datetime import datetime, timezone

import pytest
import pytest_asyncio
from sqlalchemy.ext.asyncio import AsyncSession

from artiFACT.kernel.models import FcFact, FcFactVersion, FcNode, FcUser
from artiFACT.modules.search.service import search_facts, search_facts_flat
from artiFACT.modules.taxonomy.tree_serializer import get_program_for_node


async def _publish_fact(
    db: AsyncSession,
    node: FcNode,
    sentence: str,
    user: FcUser,
    *,
    smart_tags: list[str] | None = None,
    smart_tags_text: str = "",
) -> tuple[FcFact, FcFactVersion]:
    """Create a fact with a published version (search_vector generated by PostgreSQL)."""
    fact = FcFact(
        fact_uid=uuid.uuid4(),
        node_uid=node.node_uid,
        created_by_uid=user.user_uid,
    )
    db.add(fact)
    await db.flush()

    version = FcFactVersion(
        version_uid=uuid.uuid4(),
        fact_uid=fact.fact_uid,
        state="published",
        display_sentence=sentence,
        created_by_uid=user.user_uid,
        published_at=datetime.now(timezone.utc),
        smart_tags=smart_tags or [],
        smart_tags_text=smart_tags_text,
    )
    db.add(version)
    await db.flush()

    fact.current_published_version_uid = version.version_uid
    await db.flush()
    return fact, version


# ---------------------------------------------------------------------------
# Fixtures for program grouping tests
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def program_root(db: AsyncSession, admin_user: FcUser) -> FcNode:
    """Root node that IS a program (is_program=True)."""
    node = FcNode(
        node_uid=uuid.uuid4(),
        title="Boatwing H-12",
        slug=f"boatwing-{uuid.uuid4().hex[:8]}",
        node_depth=0,
        is_program=True,
        created_by_uid=admin_user.user_uid,
    )
    db.add(node)
    await db.flush()
    return node


@pytest_asyncio.fixture
async def program_child(
    db: AsyncSession, program_root: FcNode, admin_user: FcUser,
) -> FcNode:
    """Child node under the program root."""
    node = FcNode(
        node_uid=uuid.uuid4(),
        parent_node_uid=program_root.node_uid,
        title="SE Governance",
        slug=f"se-governance-{uuid.uuid4().hex[:8]}",
        node_depth=1,
        created_by_uid=admin_user.user_uid,
    )
    db.add(node)
    await db.flush()
    return node


@pytest_asyncio.fixture
async def second_program_root(db: AsyncSession, admin_user: FcUser) -> FcNode:
    """A second program root for multi-program tests."""
    node = FcNode(
        node_uid=uuid.uuid4(),
        title="SNIPE-B",
        slug=f"snipe-b-{uuid.uuid4().hex[:8]}",
        node_depth=0,
        is_program=True,
        created_by_uid=admin_user.user_uid,
    )
    db.add(node)
    await db.flush()
    return node


@pytest_asyncio.fixture
async def second_program_child(
    db: AsyncSession, second_program_root: FcNode, admin_user: FcUser,
) -> FcNode:
    """Child under the second program."""
    node = FcNode(
        node_uid=uuid.uuid4(),
        parent_node_uid=second_program_root.node_uid,
        title="Flight Test",
        slug=f"flight-test-{uuid.uuid4().hex[:8]}",
        node_depth=1,
        created_by_uid=admin_user.user_uid,
    )
    db.add(node)
    await db.flush()
    return node


@pytest_asyncio.fixture
async def portfolio_root(db: AsyncSession, admin_user: FcUser) -> FcNode:
    """Portfolio root (is_program=False) — its children are the programs."""
    node = FcNode(
        node_uid=uuid.uuid4(),
        title="Special Projects",
        slug=f"special-projects-{uuid.uuid4().hex[:8]}",
        node_depth=0,
        is_program=False,
        created_by_uid=admin_user.user_uid,
    )
    db.add(node)
    await db.flush()
    return node


@pytest_asyncio.fixture
async def portfolio_program(
    db: AsyncSession, portfolio_root: FcNode, admin_user: FcUser,
) -> FcNode:
    """Program node under a portfolio (depth-1, is_program=True)."""
    node = FcNode(
        node_uid=uuid.uuid4(),
        parent_node_uid=portfolio_root.node_uid,
        title="Project Alpha",
        slug=f"project-alpha-{uuid.uuid4().hex[:8]}",
        node_depth=1,
        is_program=True,
        created_by_uid=admin_user.user_uid,
    )
    db.add(node)
    await db.flush()
    return node


@pytest_asyncio.fixture
async def portfolio_leaf(
    db: AsyncSession, portfolio_program: FcNode, admin_user: FcUser,
) -> FcNode:
    """Leaf node under a portfolio program."""
    node = FcNode(
        node_uid=uuid.uuid4(),
        parent_node_uid=portfolio_program.node_uid,
        title="Requirements",
        slug=f"requirements-{uuid.uuid4().hex[:8]}",
        node_depth=2,
        created_by_uid=admin_user.user_uid,
    )
    db.add(node)
    await db.flush()
    return node


# ===========================================================================
# Blended scoring tests
# ===========================================================================


async def test_search_finds_fact_by_sentence_text(
    db: AsyncSession, admin_user: FcUser, child_node: FcNode,
) -> None:
    """Search finds facts matching sentence text."""
    await _publish_fact(
        db, child_node, "All data at rest is encrypted using RDS AES-256", admin_user,
    )
    result = await search_facts(db, "encrypted")
    assert result["total"] >= 1
    sentences = [
        r["display_sentence"] for g in result["programs"] for r in g["results"]
    ]
    assert any("encrypted" in s.lower() for s in sentences)


async def test_search_finds_fact_by_smart_tag(
    db: AsyncSession, admin_user: FcUser, child_node: FcNode,
) -> None:
    """Search finds facts via smart_tags_text even when sentence doesn't match."""
    await _publish_fact(
        db,
        child_node,
        "Program is ACAT I acquisition category",
        admin_user,
        smart_tags=["mdap"],
        smart_tags_text="mdap major defense acquisition program",
    )
    result = await search_facts(db, "mdap")
    assert result["total"] >= 1
    sentences = [
        r["display_sentence"] for g in result["programs"] for r in g["results"]
    ]
    assert any("ACAT" in s for s in sentences)


async def test_search_or_not_and(
    db: AsyncSession, admin_user: FcUser, child_node: FcNode,
) -> None:
    """Query terms are OR-joined — matches any term, not all."""
    await _publish_fact(db, child_node, "Encryption is mandatory for all data", admin_user)
    await _publish_fact(db, child_node, "FIPS compliance is required", admin_user)
    result = await search_facts(db, "encryption FIPS compliance")
    assert result["total"] >= 2


async def test_search_empty_query_returns_empty(db: AsyncSession) -> None:
    """Empty query returns empty result, no error."""
    result = await search_facts(db, "")
    assert result == {"programs": [], "total": 0}

    result2 = await search_facts(db, "   ")
    assert result2 == {"programs": [], "total": 0}


async def test_search_excludes_retired_facts(
    db: AsyncSession, admin_user: FcUser, child_node: FcNode,
) -> None:
    """Retired facts are excluded from results."""
    await _publish_fact(
        db, child_node, "Active system uses cryptography standards", admin_user,
    )
    # Create a retired fact
    retired_fact = FcFact(
        fact_uid=uuid.uuid4(),
        node_uid=child_node.node_uid,
        created_by_uid=admin_user.user_uid,
        is_retired=True,
        retired_at=datetime.now(timezone.utc),
    )
    db.add(retired_fact)
    await db.flush()
    retired_version = FcFactVersion(
        version_uid=uuid.uuid4(),
        fact_uid=retired_fact.fact_uid,
        state="published",
        display_sentence="Retired fact about cryptography standards",
        created_by_uid=admin_user.user_uid,
        published_at=datetime.now(timezone.utc),
    )
    db.add(retired_version)
    await db.flush()
    retired_fact.current_published_version_uid = retired_version.version_uid
    await db.flush()

    result = await search_facts(db, "cryptography standards")
    all_sentences = [
        r["display_sentence"] for g in result["programs"] for r in g["results"]
    ]
    assert any("Active" in s for s in all_sentences)
    assert not any("Retired" in s for s in all_sentences)


async def test_display_sentence_not_truncated(
    db: AsyncSession, admin_user: FcUser, child_node: FcNode,
) -> None:
    """display_sentence is returned in full, never truncated."""
    long_sentence = "The comprehensive system authorization boundary includes " + "x" * 200
    await _publish_fact(db, child_node, long_sentence, admin_user)
    result = await search_facts(db, "comprehensive authorization boundary")
    all_sentences = [
        r["display_sentence"] for g in result["programs"] for r in g["results"]
    ]
    assert long_sentence in all_sentences


# ===========================================================================
# Program grouping tests
# ===========================================================================


async def test_results_grouped_by_program(
    db: AsyncSession,
    admin_user: FcUser,
    program_child: FcNode,
    second_program_child: FcNode,
) -> None:
    """Results from different programs appear under separate program groups."""
    await _publish_fact(
        db, program_child, "Test evaluation master plan for system", admin_user,
    )
    await _publish_fact(
        db, second_program_child, "Test flight operations procedure", admin_user,
    )
    result = await search_facts(db, "test")
    assert result["total"] >= 2
    program_titles = [g["program_title"] for g in result["programs"]]
    assert "Boatwing H-12" in program_titles
    assert "SNIPE-B" in program_titles


async def test_program_grouping_uses_is_program_flag(
    db: AsyncSession,
    admin_user: FcUser,
    portfolio_leaf: FcNode,
    portfolio_program: FcNode,
    portfolio_root: FcNode,
) -> None:
    """Results group under is_program=True ancestor, not portfolio root."""
    await _publish_fact(
        db, portfolio_leaf, "Requirements traceability matrix updated", admin_user,
    )
    result = await search_facts(db, "requirements traceability")
    assert result["total"] >= 1
    program_titles = [g["program_title"] for g in result["programs"]]
    assert "Project Alpha" in program_titles
    assert "Special Projects" not in program_titles


async def test_program_fallback_to_root(
    db: AsyncSession, admin_user: FcUser,
) -> None:
    """When no ancestor has is_program=True, fallback to root node."""
    # Create root with is_program=False
    fallback_root = FcNode(
        node_uid=uuid.uuid4(),
        title="Orphan Root",
        slug=f"orphan-root-{uuid.uuid4().hex[:8]}",
        node_depth=0,
        is_program=False,
        created_by_uid=admin_user.user_uid,
    )
    db.add(fallback_root)
    await db.flush()
    fallback_child = FcNode(
        node_uid=uuid.uuid4(),
        parent_node_uid=fallback_root.node_uid,
        title="Subchild",
        slug=f"subchild-{uuid.uuid4().hex[:8]}",
        node_depth=1,
        is_program=False,
        created_by_uid=admin_user.user_uid,
    )
    db.add(fallback_child)
    await db.flush()

    await _publish_fact(
        db, fallback_child, "Fallback scenario verification procedure", admin_user,
    )
    result = await search_facts(db, "fallback scenario verification")
    assert result["total"] >= 1
    program_titles = [g["program_title"] for g in result["programs"]]
    assert "Orphan Root" in program_titles


async def test_results_within_group_sorted_by_score(
    db: AsyncSession,
    admin_user: FcUser,
    program_child: FcNode,
) -> None:
    """Within each program group, results are ordered by score descending."""
    await _publish_fact(
        db, program_child, "Authentication is required for all users", admin_user,
    )
    await _publish_fact(
        db, program_child, "Authentication authentication is very important", admin_user,
    )
    result = await search_facts(db, "authentication")
    assert result["total"] >= 2
    for group in result["programs"]:
        scores = [r["score"] for r in group["results"]]
        assert scores == sorted(scores, reverse=True)


async def test_each_group_has_program_title_and_results(
    db: AsyncSession,
    admin_user: FcUser,
    program_child: FcNode,
) -> None:
    """Each program group has required fields."""
    await _publish_fact(
        db, program_child, "Verification testing of subsystem components", admin_user,
    )
    result = await search_facts(db, "verification testing")
    assert result["total"] >= 1
    for group in result["programs"]:
        assert "program_uid" in group
        assert "program_title" in group
        assert "results" in group
        assert isinstance(group["results"], list)
        for r in group["results"]:
            assert "fact_uid" in r
            assert "version_uid" in r
            assert "display_sentence" in r
            assert "state" in r
            assert "node_uid" in r
            assert "score" in r
            assert "breadcrumb" in r


# ===========================================================================
# is_program flag tests
# ===========================================================================


async def test_is_program_column_exists_defaults_false(
    db: AsyncSession, admin_user: FcUser,
) -> None:
    """FcNode has is_program field, defaults to False."""
    node = FcNode(
        node_uid=uuid.uuid4(),
        title="Default Test Node",
        slug=f"default-test-{uuid.uuid4().hex[:8]}",
        node_depth=0,
        created_by_uid=admin_user.user_uid,
    )
    db.add(node)
    await db.flush()
    assert node.is_program is False


async def test_get_program_for_node_finds_ancestor(
    db: AsyncSession,
    admin_user: FcUser,
    portfolio_root: FcNode,
    portfolio_program: FcNode,
    portfolio_leaf: FcNode,
) -> None:
    """get_program_for_node walks up to find is_program=True ancestor."""
    from sqlalchemy import select as sa_select

    all_result = await db.execute(
        sa_select(FcNode).where(FcNode.is_archived.is_(False))
    )
    all_nodes = list(all_result.scalars().all())

    program = get_program_for_node(all_nodes, portfolio_leaf.node_uid)
    assert program is not None
    assert program.node_uid == portfolio_program.node_uid
    assert program.title == "Project Alpha"


async def test_get_program_for_node_returns_root_as_fallback(
    db: AsyncSession, admin_user: FcUser,
) -> None:
    """When no ancestor has is_program=True, returns root."""
    from sqlalchemy import select as sa_select

    root = FcNode(
        node_uid=uuid.uuid4(),
        title="No Flag Root",
        slug=f"no-flag-root-{uuid.uuid4().hex[:8]}",
        node_depth=0,
        is_program=False,
        created_by_uid=admin_user.user_uid,
    )
    db.add(root)
    await db.flush()
    child = FcNode(
        node_uid=uuid.uuid4(),
        parent_node_uid=root.node_uid,
        title="No Flag Child",
        slug=f"no-flag-child-{uuid.uuid4().hex[:8]}",
        node_depth=1,
        is_program=False,
        created_by_uid=admin_user.user_uid,
    )
    db.add(child)
    await db.flush()

    all_result = await db.execute(
        sa_select(FcNode).where(FcNode.is_archived.is_(False))
    )
    all_nodes = list(all_result.scalars().all())

    program = get_program_for_node(all_nodes, child.node_uid)
    assert program is not None
    assert program.node_uid == root.node_uid


# ===========================================================================
# Legacy flat search tests (existing behavior preserved)
# ===========================================================================


async def test_flat_search_returns_ranked_results(
    db: AsyncSession, admin_user: FcUser, child_node: FcNode,
) -> None:
    """Flat search returns ranked results matching the query."""
    await _publish_fact(
        db, child_node, "The system owner is responsible for configuration", admin_user,
    )
    await _publish_fact(db, child_node, "Network interfaces must be documented", admin_user)
    await _publish_fact(
        db, child_node, "The system owner reviews all changes to the system", admin_user,
    )
    results = await search_facts_flat(db, "system owner")
    assert len(results) >= 2
    for i in range(len(results) - 1):
        assert results[i].rank >= results[i + 1].rank


async def test_flat_search_breadcrumbs(
    db: AsyncSession, admin_user: FcUser, root_node: FcNode, child_node: FcNode,
) -> None:
    """Flat search breadcrumbs come from in-memory tree load."""
    await _publish_fact(
        db, child_node, "The system configuration is validated annually", admin_user,
    )
    results = await search_facts_flat(db, "system configuration")
    assert len(results) >= 1
    bc = results[0].breadcrumb
    assert len(bc) >= 2
    titles = [b.title for b in bc]
    assert root_node.title in titles
    assert child_node.title in titles
