"""Tests for full-text search service."""

import uuid
from datetime import datetime, timezone

from sqlalchemy.ext.asyncio import AsyncSession

from artiFACT.kernel.models import FcFact, FcFactVersion, FcNode, FcUser
from artiFACT.modules.search.service import search_facts


async def _publish_fact(
    db: AsyncSession, node: FcNode, sentence: str, user: FcUser
) -> tuple[FcFact, FcFactVersion]:
    """Create a fact with a published version (search_vector generated by PostgreSQL)."""
    fact = FcFact(
        fact_uid=uuid.uuid4(),
        node_uid=node.node_uid,
        created_by_uid=user.user_uid,
    )
    db.add(fact)
    await db.flush()

    version = FcFactVersion(
        version_uid=uuid.uuid4(),
        fact_uid=fact.fact_uid,
        state="published",
        display_sentence=sentence,
        created_by_uid=user.user_uid,
        published_at=datetime.now(timezone.utc),
    )
    db.add(version)
    await db.flush()

    fact.current_published_version_uid = version.version_uid
    await db.flush()
    return fact, version


async def test_search_returns_ranked_results(
    db: AsyncSession, admin_user: FcUser, child_node: FcNode
):
    """Search returns ranked results matching the query."""
    await _publish_fact(
        db, child_node, "The system owner is responsible for configuration.", admin_user
    )
    await _publish_fact(db, child_node, "Network interfaces must be documented.", admin_user)
    await _publish_fact(
        db, child_node, "The system owner reviews all changes to the system.", admin_user
    )

    results = await search_facts(db, "system owner")

    assert len(results) >= 2
    # Results are ranked by ts_rank descending
    for i in range(len(results) - 1):
        assert results[i].rank >= results[i + 1].rank
    # Every result contains at least one search term
    for r in results:
        lower = r.display_sentence.lower()
        assert "system" in lower or "owner" in lower


async def test_breadcrumbs_resolved_from_cache_not_N_queries(
    db: AsyncSession, admin_user: FcUser, root_node: FcNode, child_node: FcNode
):
    """Breadcrumbs come from a single in-memory tree load, not N+1 CTEs per result (v1 B-PERF-02)."""
    await _publish_fact(
        db, child_node, "The system configuration is validated annually.", admin_user
    )

    results = await search_facts(db, "system configuration")

    assert len(results) >= 1
    bc = results[0].breadcrumb
    # Breadcrumb should contain the path: root_node → child_node
    assert len(bc) >= 2
    titles = [b.title for b in bc]
    assert root_node.title in titles
    assert child_node.title in titles
    # Root comes before child in the breadcrumb
    assert titles.index(root_node.title) < titles.index(child_node.title)


async def test_search_accessible_to_all_authenticated_users(
    db: AsyncSession,
    admin_user: FcUser,
    viewer_user: FcUser,
    contributor_user: FcUser,
    child_node: FcNode,
):
    """Search works for all authenticated users regardless of role."""
    await _publish_fact(db, child_node, "Access check fact for search validation.", admin_user)

    # The service has no role-based filtering — all users get the same results.
    # Each call below exercises the real tsvector query and real tree cache.
    for _user in [admin_user, viewer_user, contributor_user]:
        results = await search_facts(db, "access check")
        assert len(results) >= 1
        assert results[0].display_sentence == "Access check fact for search validation."
